name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_ORG: epcc
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${{ env.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin
    - name: pre-pull the base image
      run: docker pull --quiet jupyter/datascience-notebook
    - name: Build the Docker image
      run: |
        docker build \
        --file jupyter_docker/Dockerfile \
        --tag "${{ env.DOCKER_ORG }}/dawhpc:latest" \
        --tag "${{ env.DOCKER_ORG }}/dawhpc:$(git rev-parse --short HEAD)" \
        .
    - name: DockerHub push
      run: docker push --all-tags "${{ env.DOCKER_ORG }}/dawhpc"
